### ISSUE TITLE
Release through PDE Contributions Manager?

### ISSUE THREAD

**Issue by jeremydouglass** [Izza11/shader-mode#4]
Now that it is 1.0, have you considered submitting this mode to PDE Contributions Manager so that it can be installed automatically through PDE?

**Comment by flashblaze** [comment]
What version are you on? It is available on 3.5.3

**Comment by jeremydouglass** [comment]
Oops -- I had accidentally checked it on my copy of 3.4.
Yes, I can see it and installed it correctly on my 3.5.4.

**Comment by jeremydouglass** [comment]
note: was in: https://github.com/processing/processing-docs/commit/67d6852577
